In [68]:
import pandas as pd
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('anatel_total_pat.csv')

In [3]:
df=df.fillna(0)

In [4]:
df.sample()

,Grupo,Raz�o Social,CNPJ,Regi�o,UF,Munic�pio,C�digo Munic�pio,Tecnologia,Faixa,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05
63,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,GO,Goi�nia,5208707,Fibra,> 34Mbps,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [5]:
df.Faixa.unique()

array(['0Kbps a 512Kbps', '12Mbps a 34Mbps', '2Mbps a 12Mbps',
       '512kbps a 2Mbps', '> 34Mbps'], dtype=object)

https://datatofish.com/if-condition-in-pandas-dataframe/

In [6]:
df.loc[(df.Faixa == '0Kbps a 512Kbps'), 'velo'] = 0.256
df.loc[(df.Faixa == '512kbps a 2Mbps'), 'velo'] = 1.256
df.loc[(df.Faixa == '2Mbps a 12Mbps'), 'velo'] = 7
df.loc[(df.Faixa == '12Mbps a 34Mbps'), 'velo'] = 23
df.loc[(df.Faixa == '> 34Mbps'), 'velo'] = 34

In [7]:
for x in df.columns[9:-1]:
    df[f'{x}_v'] = df[x]*df['velo']

In [14]:
mes_orig=df.columns[9:62]

In [15]:
mes_velo=df.columns[63:]

In [16]:
assert len(mes_orig)==len(mes_velo)

In [27]:
cidades=df['Munic�pio'].unique()

In [30]:
tecnologia=df['Tecnologia'].unique()

In [9]:
df.sample(1)

,Grupo,Raz�o Social,CNPJ,Regi�o,UF,Munic�pio,C�digo Munic�pio,Tecnologia,Faixa,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,velo,2015-01_v,2015-02_v,2015-03_v,2015-04_v,2015-05_v,2015-06_v,2015-07_v,2015-08_v,2015-09_v,2015-10_v,2015-11_v,2015-12_v,2016-01_v,2016-02_v,2016-03_v,2016-04_v,2016-05_v,2016-06_v,2016-07_v,2016-08_v,2016-09_v,2016-10_v,2016-11_v,2016-12_v,2017-01_v,2017-02_v,2017-03_v,2017-04_v,2017-05_v,2017-06_v,2017-07_v,2017-08_v,2017-09_v,2017-10_v,2017-11_v,2017-12_v,2018-01_v,2018-02_v,2018-03_v,2018-04_v,2018-05_v,2018-06_v,2018-07_v,2018-08_v,2018-09_v,2018-10_v,2018-11_v,2018-12_v,2019-01_v,2019-02_v,2019-03_v,2019-04_v,2019-05_v
415,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Sudeste,MG,Delta,3121258,ETHERNET,0Kbps a 512Kbps,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.256,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512,0.0,0.512

In [17]:
for x,y in zip(mes_orig,mes_velo):
    print(x,y)
    break

2015-01 2015-01_v

In [24]:
df[df['Munic�pio']=='Bras�lia']['Tecnologia'].unique()#head()#['2015-01'].sum()

array(['ETHERNET', 'xDSL'], dtype=object)

In [43]:
df[(df['Munic�pio']=='Bras�lia') & (df['Tecnologia']=='ETHERNET')]#['Tecnologia'].unique()[0]

,Grupo,Raz�o Social,CNPJ,Regi�o,UF,Munic�pio,C�digo Munic�pio,Tecnologia,Faixa,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,velo,2015-01_v,2015-02_v,2015-03_v,2015-04_v,2015-05_v,2015-06_v,2015-07_v,2015-08_v,2015-09_v,2015-10_v,2015-11_v,2015-12_v,2016-01_v,2016-02_v,2016-03_v,2016-04_v,2016-05_v,2016-06_v,2016-07_v,2016-08_v,2016-09_v,2016-10_v,2016-11_v,2016-12_v,2017-01_v,2017-02_v,2017-03_v,2017-04_v,2017-05_v,2017-06_v,2017-07_v,2017-08_v,2017-09_v,2017-10_v,2017-11_v,2017-12_v,2018-01_v,2018-02_v,2018-03_v,2018-04_v,2018-05_v,2018-06_v,2018-07_v,2018-08_v,2018-09_v,2018-10_v,2018-11_v,2018-12_v,2019-01_v,2019-02_v,2019-03_v,2019-04_v,2019-05_v
0,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,DF,Bras�lia,5300108,ETHERNET,0Kbps a 512Kbps,56.0,0.0,52.0,0.0,54.0,0.0,56.0,0.0,57.0,0.0,56.0,0.0,56.0,0.0,55.0,0.0,49.0,0.0,43.0,0.0,46.0,0.0,43.0,0.0,42.0,0.0,43.0,0.0,43.0,0.0,44.0,0.0,43.0,0.0,45.0,0.0,45.0,0.0,42.0,0.0,40.0,0.0,40.0,0.0,41.0,0.0,41.0,0.0,42.0,0.0,42.0,0.0,33.0,0.256,14.336,0.0,13.312,0.0,13.824,0.0,14.336,0.0,14.592,0.0,14.336,0.0,14.336,0.0,14.08,0.0,12.544,0.0,11.008,0.0,11.776,0.0,11.008,0.0,10.752,0.0,11.008,0.0,11.008,0.0,11.264,0.0,11.008,0.0,11.520,0.0,11.520,0.0,10.752,0.0,10.240,0.0,10.240,0.0,10.496,0.0,10.496,0.0,10.752,0.0,10.752,0.0,8.448
1,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,DF,Bras�lia,5300108,ETHERNET,12Mbps a 34Mbps,18.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,15.0,0.0,16.0,0.0,18.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,16.0,0.0,17.0,0.0,17.0,0.0,17.0,0.0,19.0,0.0,20.0,0.0,20.0,0.0,19.0,0.0,19.0,0.0,18.0,0.0,19.0,0.0,20.0,0.0,21.0,0.0,21.0,23.000,414.000,0.0,368.000,0.0,368.000,0.0,368.000,0.0,368.000,0.0,345.000,0.0,368.000,0.0,414.00,0.0,368.000,0.0,368.000,0.0,368.000,0.0,368.000,0.0,368.000,0.0,368.000,0.0,391.000,0.0,391.000,0.0,391.000,0.0,437.000,0.0,460.000,0.0,460.000,0.0,437.000,0.0,437.000,0.0,414.000,0.0,437.000,0.0,460.000,0.0,483.000,0.0,483.000
2,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,DF,Bras�lia,5300108,ETHERNET,2Mbps a 12Mbps,40.0,0.0,40.0,0.0,42.0,0.0,42.0,0.0,41.0,0.0,45.0,0.0,44.0,0.0,46.0,0.0,48.0,0.0,49.0,0.0,48.0,0.0,52.0,0.0,51.0,0.0,51.0,0.0,51.0,0.0,54.0,0.0,55.0,0.0,61.0,0.0,64.0,0.0,66.0,0.0,64.0,0.0,66.0,0.0,66.0,0.0,66.0,0.0,70.0,0.0,68.0,0.0,80.0,7.000,280.000,0.0,280.000,0.0,294.000,0.0,294.000,0.0,287.000,0.0,315.000,0.0,308.000,0.0,322.00,0.0,336.000,0.0,343.000,0.0,336.000,0.0,364.000,0.0,357.000,0.0,357.000,0.0,357.000,0.0,378.000,0.0,385.000,0.0,427.000,0.0,448.000,0.0,462.000,0.0,448.000,0.0,462.000,0.0,462.000,0.0,462.000,0.0,490.000,0.0,476.000,0.0,560.000
3,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,DF,Bras�lia,5300108,ETHERNET,512kbps a 2Mbps,82.0,0.0,83.0,0.0,87.0,0.0,85.0,0.0,85.0,0.0,86.0,0.0,87.0,0.0,85.0,0.0,85.0,0.0,86.0,0.0,86.0,0.0,86.0,0.0,89.0,0.0,89.0,0.0,89.0,0.0,90.0,0.0,91.0,0.0,88.0,0.0,92.0,0.0,94.0,0.0,98.0,0.0,97.0,0.0,102.0,0.0,103.0,0.0,103.0,0.0,101.0,0.0,102.0,1.256,102.992,0.0,104.248,0.0,109.272,0.0,106.760,0.0,106.760,0.0,108.016,0.0,109.272,0.0,106.76,0.0,106.760,0.0,108.016,0.0,108.016,0.0,108.016,0.0,111.784,0.0,111.784,0.0,111.784,0.0,113.040,0.0,114.296,0.0,110.528,0.0,115.552,0.0,118.064,0.0,123.088,0.0,121.832,0.0,128.112,0.0,129.368,0.0,129.368,0.0,126.856,0.0,128.112
4,ALGAR (CTBC TELECOM),ALGAR MULTIM�DIA S/A,04.622.116/0001-13,Centro-Oeste,DF,Bras�lia,5300108,ETHERNET,> 34Mbps,32.0,0.0,32.0,0.0,33.0,0.0,33.0,0.0,33.0,0.0,32.0,0.0,36.0,0.0,40.0,0.0,40.0,0.0,38.0,0.0,38.0,0.0,39.0,0.0,37.0,0.0,37.0,0.0,37.0,0.0,36.0,0.0,37.0,0.0,37.0,0.0,37.0,0.0,36.0,0.0,35.0,0.0,35.0,0.0,36.0,0.0,37.0,0.0,36.0,0.0,37.0,0.0,38.0,34.000,1088.000,0.0,1088.000,0.0,1122.000,0.0,1122.000,0.0,1122.000,0.0,1088.000,0.0,1224.000,0.0,1360.00,0.0,1360.000,0.0,1292.000,0.0,1292.000,0.0,1326.000,0.0,1258.000,0.0,1258.000,0.0,1258.000,0.0,1224.000,0.0,1258.000,0.0,1258.000,0.0,1258.000,0.0,1224.000,0.0,1190.000,0.0,1190.000,0.0,1224.000,0.0,1258.000,0.0,1224.000,0.0,1258.000,0.0,1292.000

In [40]:
testao=df[(df['Munic�pio']=='Bras�lia') & (df['Tecnologia']=='ETHERNET')]
print(testao['2015-01'].sum())
print(testao['2015-01_v'].sum())
print(testao['2015-01_v'].sum()/testao['2015-01'].sum())

228.0
1899.328
8.330385964912281

In [44]:
listao=[]
#separar e correr as cidades
for cidade in cidades:
    temp=df[df['Munic�pio']==cidade]
    
    #separar e correr as tecnologias
    for tecno in tecnologia:
        try:
            temp1=temp[temp['Tecnologia']==tecno]
            for x,y in zip(mes_orig,mes_velo):
                total_conexoes=temp1[x].sum()
                total_velo=temp1[y].sum()
                media=total_velo/total_conexoes
                grupo=temp1['Grupo'].unique()[0]
                tex=temp1['Tecnologia'].unique()[0]
                listao.append([grupo,cidade,x,tex,media])    
        except:
            pass

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]

In [53]:
fim=pd.DataFrame(listao, columns=['grupo','cidade','mes','tec','media'])

In [57]:
fim=fim.dropna(how='any')

In [58]:
fim.sample()

                      grupo   cidade      mes   tec  media
10237  ALGAR (CTBC TELECOM)  Igarap�  2015-09  xDSL  1.256

In [78]:
df[df['Munic�pio']=='Bras�lia'].groupby(['Grupo'])[df.columns[63:]].agg(['sum'])

,2015-01_v,2015-02_v,2015-03_v,2015-04_v,2015-05_v,2015-06_v,2015-07_v,2015-08_v,2015-09_v,2015-10_v,2015-11_v,2015-12_v,2016-01_v,2016-02_v,2016-03_v,2016-04_v,2016-05_v,2016-06_v,2016-07_v,2016-08_v,2016-09_v,2016-10_v,2016-11_v,2016-12_v,2017-01_v,2017-02_v,2017-03_v,2017-04_v,2017-05_v,2017-06_v,2017-07_v,2017-08_v,2017-09_v,2017-10_v,2017-11_v,2017-12_v,2018-01_v,2018-02_v,2018-03_v,2018-04_v,2018-05_v,2018-06_v,2018-07_v,2018-08_v,2018-09_v,2018-10_v,2018-11_v,2018-12_v,2019-01_v,2019-02_v,2019-03_v,2019-04_v,2019-05_v
,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum
Grupo,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ALGAR (CTBC TELECOM),5822.936,0.0,5965.68,0.0,6331.216,0.0,6434.472,0.0,6382.984,0.0,6544.728,0.0,6796.984,0.0,6969.728,0.0,7086.192,0.0,7323.912,0.0,7506.216,0.0,7795.68,0.0,7907.68,0.0,7989.936,0.0,8334.168,0.0,8495.936,0.0,8887.936,0.0,9375.68,0.0,9875.24,0.0,10260.984,0.0,10532.472,0.0,10749.96,0.0,11141.984,0.0,11462.496,0.0,11790.752,0.0,12139.752,0.0,12668.704

In [62]:
for x in df['Munic�pio'].unique():
    temp=df[df['Munic�pio']==x]

array(['Bras�lia', 'Alex�nia', 'An�polis', 'Aparecida de Goi�nia',
       'Bela Vista de Goi�s', 'Buriti Alegre', 'Cachoeira Alta',
       'Cachoeira Dourada', 'Caldas Novas', 'Catal�o', 'Ca�u',
       'Cristalina', 'Ed�ia', 'Goiatuba', 'Goi�nia', 'Hidrol�ndia',
       'Inaciol�ndia', 'Itumbiara', 'Jata�', 'Luzi�nia', 'Morrinhos',
       'Novo Gama', 'Palmeiras de Goi�s', 'Paranaiguara', 'Quirin�polis',
       'Rio Quente', 'Rio Verde', 'Santa Helena de Goi�s',
       'Senador Canedo', 'S�o Sim�o', 'Terez�polis de Goi�s', 'Trindade',
       'Valpara�so de Goi�s', '�guas Lindas de Goi�s', 'Campo Grande',
       'Cassil�ndia', 'Parana�ba', 'Cuiab�', 'S�o F�lix do Araguaia',
       'Macei�', 'Cama�ari', "Dias d'�vila", 'Feira de Santana',
       'Salvador', 'Fortaleza', 'S�o Lu�s', 'Vargem Grande',
       'Cabo de Santo Agostinho', 'Jaboat�o dos Guararapes', 'Paulista',
       'Recife', 'Natal', 'Parnamirim', 'Aracaju', 'Manaus', 'Bel�m',
       'Cariacica', 'Serra', 'Vila Velha', 'Vit�ria', 'Abaet�', 'Alfenas',
       'Araguari', 'Arapor�', 'Arax�', 'Ara�jos', 'Arceburgo', 'Bambu�',
       'Barbacena', 'Belo Horizonte', 'Betim', 'Bom Despacho',
       'Brumadinho', 'Caet�', 'Campina Verde', 'Campo Florido',
       'Campos Altos', 'Can�polis', 'Capin�polis', 'Caratinga',
       'Carmo do Cajuru', 'Carmo do Parana�ba', 'Carneirinho',
       'Centralina', 'Cl�udio', 'Comendador Gomes',
       'Concei��o das Alagoas', 'Concei��o do Par�', 'Confins',
       'Congonhas', 'Conquista', 'Conselheiro Lafaiete', 'Contagem',
       'Coromandel', 'Cruzeiro da Fortaleza', 'C�rrego Danta', 'Delta',
       'Divin�polis', 'Esmeraldas', 'Extrema', 'Formiga', 'Fronteira',
       'Frutal', 'Governador Valadares', 'Gurinhat�', 'Ibiraci', 'Ibirit�',
       'Ibi�', 'Igarap�', 'Igaratinga', 'Iguatama', 'Indian�polis',
       'Ipatinga', 'Ipia�u', 'Itabira'], dtype=object)

In [ ]:
df.groupby(['Grupo','Munic�pio','Tecnologia','velo'])[df.columns[63:]].sum()

In [22]:
df.dtypes

Grupo                object
Raz�o Social         object
CNPJ                 object
Regi�o               object
UF                   object
Munic�pio            object
C�digo Munic�pio      int64
Tecnologia           object
Faixa                object
2015-01             float64
2015-02             float64
2015-03             float64
2015-04             float64
2015-05             float64
2015-06             float64
2015-07             float64
2015-08             float64
2015-09             float64
2015-10             float64
2015-11             float64
2015-12             float64
2016-01             float64
2016-02             float64
2016-03             float64
2016-04             float64
2016-05             float64
2016-06             float64
2016-07             float64
2016-08             float64
2016-09             float64
2016-10             float64
2016-11             float64
2016-12             float64
2017-01             float64
2017-02             float64
2017-03             float64
2017-04             float64
2017-05             float64
2017-06             float64
2017-07             float64
2017-08             float64
2017-09             float64
2017-10             float64
2017-11             float64
2017-12             float64
2018-01             float64
2018-02             float64
2018-03             float64
2018-04             float64
2018-05             float64
2018-06             float64
2018-07             float64
2018-08             float64
2018-09             float64
2018-10             float64
2018-11             float64
2018-12             float64
2019-01             float64
2019-02             float64
2019-03             float64
2019-04             float64
2019-05             float64
dtype: object